import Head from 'next/head'
import {Container} from "react-bootstrap"
import TopComponent from '../components/TopComponent';


const Home = () => {
  return (
    <div>
      <Head>
        <title>MoDo Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
  crossorigin="anonymous"
/>
      </Head>

      <main>
        <TopComponent />
      </main>

      <footer>
      <script src="https://unpkg.com/react/umd/react.production.min.js" crossOrigin></script>

<script
  src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
  crossorigin></script>

<script
  src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
  crossorigin></script>
      </footer>
    </div>
  )
}

export default Home;
